# Generated by Django 4.2.10 on 2024-03-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dating_platform', models.CharField(max_length=255)),
                ('other_dating_platform', models.CharField(blank=True, max_length=255, null=True)),
                ('reported_username', models.CharField(max_length=255)),
                ('experience_rating', models.IntegerField()),
                ('situation_explanation', models.TextField()),
                ('uploaded_file_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
