# Generated by Django 4.2.10 on 2024-03-18 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myASD', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'permissions': [('can_access_admin_page', 'Can access admin page')]},
        ),
    ]
