# Generated by Django 4.2.10 on 2024-04-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myASD', '0005_alter_submission_dating_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='uploaded_file_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
