# Generated by Django 4.2.10 on 2024-04-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myASD', '0006_alter_submission_uploaded_file_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='uploaded_file_url',
            new_name='uploaded_file_urls',
        ),
    ]
