# Generated by Django 4.2.10 on 2024-04-15 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myASD', '0007_rename_uploaded_file_url_submission_uploaded_file_urls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='uploaded_file_urls',
            new_name='uploaded_file_paths',
        ),
    ]
