# Generated by Django 4.2.10 on 2024-04-15 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myASD', '0008_rename_uploaded_file_urls_submission_uploaded_file_paths'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='uploaded_file_paths',
            new_name='uploaded_file_urls',
        ),
    ]
